# Generated by Django 2.1 on 2018-08-16 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vg', '0002_auto_20180816_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='assigned_to',
            field=models.ManyToManyField(null=True, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
