# Generated by Django 2.1 on 2018-08-16 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vg', '0003_auto_20180816_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
